version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-container
    volumes:
      - .:/var/app
    working_dir: /var/app/
    ports:
      - 3000:3000
    command: sleep infinity
    # links:
    # - "redis"
    # redis:
  # restart: always
  # container_name: redis-container
  # image: redis:latest
  # volumes:
  # - ./store/redis:/data
  # ports:
  # - "6379:6379"
  # command: redis-server --appendonly yes
